-- Taxonomy admin override audit actions

ALTER TYPE "AdminAuditAction" ADD VALUE IF NOT EXISTS 'TAXONOMY_CASCADE_DEACTIVATE';
ALTER TYPE "AdminAuditAction" ADD VALUE IF NOT EXISTS 'TAXONOMY_FORCE_DEACTIVATE';
ALTER TYPE "AdminAuditAction" ADD VALUE IF NOT EXISTS 'TAXONOMY_REASSIGN_SUBCATEGORY';
ALTER TYPE "AdminAuditAction" ADD VALUE IF NOT EXISTS 'TAXONOMY_OVERRIDE_BILLING_GRANULARITY';
ALTER TYPE "AdminAuditAction" ADD VALUE IF NOT EXISTS 'TAXONOMY_OVERRIDE_EXECUTION';
ALTER TYPE "AdminAuditAction" ADD VALUE IF NOT EXISTS 'TAXONOMY_MERGE_SUBCATEGORIES';
ALTER TYPE "AdminAuditAction" ADD VALUE IF NOT EXISTS 'TAXONOMY_HARD_DELETE';
ALTER TYPE "AdminAuditAction" ADD VALUE IF NOT EXISTS 'TAXONOMY_BULK_APPROVE_CATALOG';
